---
name: Automerge

on:
  pull_request:
    inputs:
      tfcheck:
        description: 'Enter the tfcheck action name.'
        required: false
        type: string
    secrets:
      GITHUB:
        description: 'GitHub Token'
        required: false

jobs:
  static-checks:
    name: Check the status of static checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tf-checks: ["tf-lint / tflint", "tfsec / tfsec sarif report", "basic / Check code format"]
    steps:
      - name: Wait for "${{ matrix.tf-checks }}" to succeed
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: ${{ matrix.tf-checks }}
          repo-token: ${{ secrets.GITHUB }}
          wait-interval: 30

      - name: check for testing
        run: ls -la
...
